# Generated by Django 3.2.5 on 2021-07-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0009_auto_20210727_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingrecording',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
