# Generated by Django 3.2.5 on 2021-07-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0010_testingrecording_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingrecording',
            name='n_scenarios',
            field=models.IntegerField(default=0),
        ),
    ]
