# Generated by Django 3.2.5 on 2021-07-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0011_testingrecording_n_scenarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingrecording',
            name='img_minister',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='testingrecording',
            name='img_stats',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
