# Generated by Django 3.2.5 on 2021-07-29 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0012_auto_20210728_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparationObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code0', models.TextField(blank=True, default='', max_length=2000)),
                ('code1', models.TextField(blank=True, default='', max_length=2000)),
                ('code2', models.TextField(blank=True, default='', max_length=2000)),
                ('code4', models.TextField(blank=True, default='', max_length=2000)),
                ('code5', models.TextField(blank=True, default='', max_length=2000)),
                ('n_targets', models.IntegerField(default=1)),
                ('dists', models.TextField(blank=True, default='', max_length=2000)),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('obj1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj1',
                                           to='diagnosis.testingrecording')),
                ('obj2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj2',
                                           to='diagnosis.testingrecording')),
            ],
        ),
    ]
