# Generated by Django 3.2.5 on 2021-07-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0013_comparationobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparationobject',
            name='title',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
