# Generated by Django 3.2.5 on 2021-08-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0014_comparationobject_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComparationObject',
        ),
    ]
