# Generated by Django 3.2.7 on 2021-10-05 09:42

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0017_auto_20210908_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingrecording',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 9, 42, 37, 769441, tzinfo=utc)),
        ),
    ]
