# Generated by Django 3.2.7 on 2021-10-06 09:22

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0018_alter_testingrecording_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariosset',
            name='validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testingrecording',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 9, 22, 24, 361525, tzinfo=utc)),
        ),
    ]
