# Generated by Django 3.2.7 on 2021-10-06 15:19

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0019_auto_20211006_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingrecording',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 15, 19, 25, 165426, tzinfo=utc)),
        ),
    ]
