# Generated by Django 3.2.7 on 2021-10-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0019_testingrecording_build_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testingrecording',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='testingrecording',
            name='cm',
        ),
        migrations.RemoveField(
            model_name='testingrecording',
            name='f2f',
        ),
        migrations.RemoveField(
            model_name='testingrecording',
            name='gw',
        ),
        migrations.RemoveField(
            model_name='testingrecording',
            name='gwp',
        ),
        migrations.RemoveField(
            model_name='testingrecording',
            name='ov',
        ),
        migrations.RemoveField(
            model_name='testingrecording',
            name='ovn',
        ),
        migrations.RemoveField(
            model_name='testingrecording',
            name='sp',
        ),
        migrations.RemoveField(
            model_name='testingrecording',
            name='sve',
        ),
        migrations.RemoveField(
            model_name='testingrecording',
            name='vrb',
        ),
        migrations.RemoveField(
            model_name='testingrecording',
            name='vrf',
        ),
    ]
