# Generated by Django 3.2.7 on 2021-10-06 15:30

import datetime

import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0020_alter_testingrecording_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='course1',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='course2',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='dist1',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='dist2',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='peleng1',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='peleng2',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='vel1',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='vel2',
        ),
        migrations.AddField(
            model_name='scenario',
            name='courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0], size=None),
        ),
        migrations.AddField(
            model_name='scenario',
            name='dists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0], size=None),
        ),
        migrations.AddField(
            model_name='scenario',
            name='pelengs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0], size=None),
        ),
        migrations.AddField(
            model_name='scenario',
            name='vels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0], size=None),
        ),
        migrations.AlterField(
            model_name='testingrecording',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 15, 30, 48, 63942, tzinfo=utc)),
        ),
    ]
