# Generated by Django 3.2.7 on 2021-10-06 21:38

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0023_auto_20211007_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='type',
            field=models.IntegerField(
                choices=[(0, 'Face to face'), (1, 'Overtaken'), (2, 'Overtake'), (3, 'Give way'), (4, 'Save'),
                         (5, 'Give way priority'), (6, 'Save priority'), (7, 'Cross move'), (8, 'Cross in'),
                         (9, 'Vision restricted forward'), (10, 'Vision restricted backward')], default=0),
        ),
        migrations.AlterField(
            model_name='testingrecording',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 21, 38, 15, 100566, tzinfo=utc)),
        ),
    ]
