# Generated by Django 3.2.7 on 2021-10-06 21:42

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0024_auto_20211007_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingrecording',
            name='ci',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testingrecording',
            name='cm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testingrecording',
            name='f2f',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testingrecording',
            name='gw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testingrecording',
            name='gwp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testingrecording',
            name='ov',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testingrecording',
            name='ovn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testingrecording',
            name='sp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testingrecording',
            name='sve',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testingrecording',
            name='vrb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testingrecording',
            name='vrf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testingrecording',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 21, 42, 8, 916725, tzinfo=utc)),
        ),
    ]
