# Generated by Django 3.2.7 on 2021-10-06 21:57

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0025_auto_20211007_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingrecording',
            name='sc_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='diagnosis.scenariosset'),
        ),
        migrations.AlterField(
            model_name='testingrecording',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 21, 57, 40, 892006, tzinfo=utc)),
        ),
    ]
